# Generated by Django 3.0.3 on 2020-09-17 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='profile_img',
        ),
    ]
