# Generated by Django 3.0.3 on 2020-09-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_remove_user_info_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='Profile_image'),
        ),
    ]
