# Generated by Django 3.0.3 on 2020-09-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20200917_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
