# Generated by Django 3.0.3 on 2020-09-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_auto_20200920_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.ImageField(blank=True, upload_to='profile_image/'),
        ),
    ]
