# Generated by Django 3.0.3 on 2020-09-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_auto_20200920_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='game_slug',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
