# Generated by Django 3.1.1 on 2020-09-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0021_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='mac_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
