# Generated by Django 3.1.1 on 2020-09-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_cart_mac_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
