# Generated by Django 3.1.1 on 2020-10-03 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0023_auto_20200927_0631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_slug', models.CharField(blank=True, max_length=250)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('parent_id', models.CharField(blank=True, max_length=250)),
                ('reply', models.CharField(blank=True, max_length=250)),
                ('profile_image', models.CharField(blank=True, max_length=250)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
