# Generated by Django 3.1.1 on 2020-10-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0024_comments_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments_reply',
            name='game_slug',
        ),
    ]
