# Generated by Django 3.1.1 on 2020-10-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0025_remove_comments_reply_game_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_reply',
            name='parent_username',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
