# Generated by Django 3.1.1 on 2020-10-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0026_comments_reply_parent_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_reply',
            name='parent_id',
            field=models.IntegerField(blank=True),
        ),
    ]
