# Generated by Django 3.1.1 on 2020-10-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0027_auto_20201003_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='has_reply',
            field=models.BooleanField(default=False),
        ),
    ]
