# Generated by Django 3.1.1 on 2020-10-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0029_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_rating',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_rating',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
