# Generated by Django 3.1.1 on 2020-10-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0031_auto_20201005_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='liked',
            field=models.IntegerField(default=0),
        ),
    ]
