# Generated by Django 3.1.1 on 2020-10-30 15:23

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0035_user_info_disliked_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='disliked_comments',
            field=jsonfield.fields.JSONField(default='[]'),
        ),
    ]
