# Generated by Django 3.1.1 on 2020-10-30 15:24

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0036_auto_20201030_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='disliked_comments',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
