# Generated by Django 3.1.1 on 2020-10-31 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0039_auto_20201031_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='desc',
        ),
    ]
