# Generated by Django 3.1.1 on 2020-11-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0040_remove_cart_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='average_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
