# Generated by Django 3.1.1 on 2020-11-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0042_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='metacritic',
            field=models.IntegerField(default=0),
        ),
    ]
