# Generated by Django 3.1.1 on 2020-11-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0043_auto_20201102_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='metacritic',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
