# Generated by Django 3.1.1 on 2020-11-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0044_auto_20201102_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='release_date',
            field=models.CharField(blank=True, default=None, max_length=250),
        ),
    ]
