# Generated by Django 3.1.1 on 2020-11-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0045_auto_20201102_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='game_image',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='metacritic',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='release_date',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
